# Fragment: sops-nix per-machine key configuration.
# Applied to every machine via the universal module.
# Uses the machine's SSH host key as the age identity — zero extra key infrastructure.
# The host key is auto-generated by NixOS on first boot at /etc/ssh/ssh_host_ed25519_key.
#
# SOPS recipient setup (run once per machine after first boot):
#   nix-shell -p ssh-to-age --run \
#     'ssh-keyscan <hostname> | ssh-to-age'
# Add the printed age pubkey to .sops.yaml under the machine's anchor.
{ ... }: {
  sops = {
    # Derive the age identity from the machine's SSH host key.
    # This file is present on every NixOS machine from first boot — no separate
    # key generation step required.
    age.sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];

    # Default secrets file location. Individual sops.secrets.* entries can
    # override this, but having a default keeps per-secret declarations concise.
    defaultSopsFile = "/run/secrets/machine.yaml";
  };
}
